yelingling/huarun/urls.py
from django.conf.urls import url

from huarun.views import *

urlpatterns = [
    url(r'^index/$',index,name='home'),
    url(r'^login/$',login,name='login'),
    url(r'^register/$',register,name='register'),
    url(r'^goodcart/$',goodcart,name='goodcart'),
    url(r'^goodsInfo/(\d+)/$',newsgoods,name='goodsInfo'),
    url(r'^logout/$',logout,name='logout'),
]

yelingling/yelingling/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^huarun/',include('huarun.urls',namespace='huarun'))
]

yelingling/huarun/models.py
from django.db import models

# Create your models here.
class Lunbo(models.Model):
    src = models.CharField(max_length=200)

  # {
  #   "id":3,
  #   "type":"enjoycity",
  #   "src":"../images/12970750_180X180.jpg",
  #   "name":"【全国配送】KanS韩束橄榄卸妆水200ml",
  #   "intro":"【全国配】",
  #   "price":"29",
  #   "e_name":"",
  #   "del":"",
  #   "smallimg1":"../images/12970750_85X85.jpg",
  #   "smallimg2":"../images/12970752_85X85.jpg",
  #   "smallimg3":"../images/12970749_85X85.jpg",
  #   "smallimg4":"../images/12970751_85X85.jpg",
  #   "smallimg5":"../images/12970751_85X85.jpg",
  #   "bigimg":"../images/p_4380020.png"
  # },
class Enjoycity(models.Model):
    type = models.CharField(max_length=50)
    src = models.CharField(max_length=100)
    name = models.CharField(max_length=200)
    intro = models.CharField(max_length=30)
    price = models.IntegerField(max_length=10)
    smallimg1 = models.CharField(max_length=100)
    smallimg2= models.CharField(max_length=100)
    smallimg3 = models.CharField(max_length=100)
    smallimg4 = models.CharField(max_length=100)
    smallimg5 = models.CharField(max_length=100)
    bigimg = models.CharField(max_length=100)

class Fresh(models.Model):
    type = models.CharField(max_length=50)
    src = models.CharField(max_length=100)
    name = models.CharField(max_length=200)
    intro = models.CharField(max_length=30)
    price = models.IntegerField(max_length=10)
    smallimg1 = models.CharField(max_length=100)
    smallimg2= models.CharField(max_length=100)
    smallimg3 = models.CharField(max_length=100)
    smallimg4 = models.CharField(max_length=100)
    smallimg5 = models.CharField(max_length=100)
    bigimg = models.CharField(max_length=100)

class Kuajin(models.Model):
    type = models.CharField(max_length=50)
    src = models.CharField(max_length=100)
    name = models.CharField(max_length=200)
    intro = models.CharField(max_length=30)
    price = models.IntegerField(max_length=10)
    smallimg1 = models.CharField(max_length=100)
    smallimg2= models.CharField(max_length=100)
    smallimg3 = models.CharField(max_length=100)
    smallimg4 = models.CharField(max_length=100)
    smallimg5 = models.CharField(max_length=100)
    bigimg = models.CharField(max_length=100)

class Newsgoods(models.Model):
    type = models.CharField(max_length=50)
    src = models.CharField(max_length=100)
    price = models.IntegerField(max_length=10)
    intro = models.CharField(max_length=200)
    name = models.CharField(max_length=30)

    smallimg1 = models.CharField(max_length=100)
    smallimg2= models.CharField(max_length=100)
    smallimg3 = models.CharField(max_length=100)
    smallimg4 = models.CharField(max_length=100)
    smallimg5 = models.CharField(max_length=100)
    bigimg = models.CharField(max_length=100)

class Qianggou(models.Model):
    type = models.CharField(max_length=50)
    src = models.CharField(max_length=100)
    price = models.IntegerField(max_length=10)
    name = models.CharField(max_length=200)
    intro = models.CharField(max_length=30)

    smallimg1 = models.CharField(max_length=100)
    smallimg2= models.CharField(max_length=100)
    smallimg3 = models.CharField(max_length=100)
    smallimg4 = models.CharField(max_length=100)
    smallimg5 = models.CharField(max_length=100)
    bigimg = models.CharField(max_length=100)

class Topgoods(models.Model):
    type = models.CharField(max_length=50)
    src = models.CharField(max_length=100)
    price = models.IntegerField(max_length=10)
    name = models.CharField(max_length=200)
    intro = models.CharField(max_length=30)

    smallimg1 = models.CharField(max_length=100)
    smallimg2= models.CharField(max_length=100)
    smallimg3 = models.CharField(max_length=100)
    smallimg4 = models.CharField(max_length=100)
    smallimg5 = models.CharField(max_length=100)
    bigimg = models.CharField(max_length=100)

# 用户
class User(models.Model):
    name = models.CharField(max_length=18, unique=True)
    phone = models.IntegerField(max_length=30)
    pwd = models.CharField(max_length=32)

yelingling/huarun/views.py
from django.shortcuts import render, redirect,reverse

# Create your views here.
from huarun.models import *


def index(request):
    lunbos = Lunbo.objects.all()
    enjoycitys =Enjoycity.objects.all()
    freshs = Fresh.objects.all()
    kuajins = Kuajin.objects.all()
    newsgoods = Newsgoods.objects.all()
    qianggous = Qianggou.objects.all()
    topgoods = Topgoods.objects.all()
    data ={
        "lunbos": lunbos,
        "enjoycitys":enjoycitys,
        "freshs":freshs,
        "kuajins":kuajins,
        "newsgoods":newsgoods,
        "qianggous":qianggous,
        "topgoods":topgoods,
        "name": "",

    }
    user = request.session.get('user',0)
    users = User.objects.filter(name=user)
    if users.exists():
        data["name"] = users.first().name
    return render(request,'index.html',context=data)


def login(request):
    if request.method == "POST":
        username = request.POST.get('username1')
        password = request.POST.get('password1')



        print(password)
        users = User.objects.filter(name=username, pwd=password)
        if users.exists():
            # 登录成功,保存登录状态，然后自动跳转到‘我的’页面
            request.session['user'] = users.first().name
            return redirect(reverse('huarun:home'))
        else:
            data = {
                "msg": '用户名或密码不正确'
            }
            return render(request, 'login.html', data)
    else:
        return render(request,'login.html')


def register(request):
    if request.method == "POST":
        username = request.POST.get('username')
        tel = request.POST.get('tel')
        password = request.POST.get('password')
        if len(username)  < 4 or len(username)  > 20 :
            data = {
                'msg': "用户名长度为4到20的字位"
            }
            return render(request, 'register.html', data)
        users = User.objects.filter(name=username)
        if users.exists():
            data = {
                'msg': "用户名已存在！"
            }
            return render(request, 'register.html', data)

        user = User()
        user.name = username
        user.phone = tel
        user.pwd = password
        user.save()
        request.session['user'] = user.name
        return redirect(reverse('huarun:home'))
    else:
        return render(request,'register.html')


def goodcart(request):

    return render(request,'goodcart.html')


def newsgoods(request,newsgood_id):
    newsgood = Newsgoods.objects.get(id = newsgood_id)
    data ={
        "newsgood":newsgood,

    }
    # context = data

    return render(request,'goodsInfo.html',context = data )

# 退出
def logout(request):
    del request.session['user']
    request.session.flush()
    return redirect(reverse('huarun:home'))

yelingling/templates/goodcart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>购物车</title>
    <link rel="stylesheet" href="../css/goodcart.css">
    <script type="text/javascript" src="/static/js/jquery-1.12.0.js"></script>
    <script type="text/javascript" src="/static/js/jquery.cookie.js"></script>
    <script type="text/javascript" src="/static/js/goodcart.js"></script>
</head>
<body>
    <div class="header">
        <div class="center">
            <div class="siteNav">
                <div class="siteNavCityChoose">
                    <span class="title">我在深圳</span>
                </div>
                <div class="siteNavLogin">
                    您好，欢迎来e万家
                    <a href="login.html">登录</a><a href="register.html">注册</a>
                </div>
                <div class="siteNavEntry">
                    <a href="">收藏夹</a>
                    <a href="">我的订单</a>
                </div>
            </div>
            <div class="headerBody">
                <a href="index.html" class="headerLogo"></a>
                <ul class="headerShoppingStep">
                    <li class="active">
                        <div class="line"></div>
                        <div class="radius">1</div>
                        <span class="title">购物车</span>
                    </li>
                    <li>
                        <div class="line"></div>
                        <div class="radius">2</div>
                        <span class="title">确认订单信息</span>
                    </li>
                    <li>
                        <div class="line"></div>
                        <div class="radius">3</div>
                        <span class="title">提交订单</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="backededed">
        <div class="mani_cat_but">
            <span class="title">购物车</span>
            <a class="but" href="index.html">继续购物 &gt;</a>
        </div>
        <div class="datles_table">
            <div class="delivery">
                <span class="totalAmount">全部商品<span>1</span>件</span>
            </div>
        </div>
        <div class="th">
            <div class="ld1 ldx">
                <div class="checkbox enableSelect active">
                    <i></i>
                </div>全选&nbsp;
            </div>
            <div class="ld2 ldx">
                商品
            </div>
            <div class="ld3 ldx">
                规格属性
            </div>
            <div class="ld4 ldx">
                单价(元)
            </div>
            <div class="ld6 ldx">
                数量
            </div>
            <div class="ld7 ldx">
                商品小计(元)
            </div>
            <div class="ld8 ldx">
                操作
            </div>
        </div>
        <ul class="ll">
            <div class="merchantHeader">
                <div class="checkbox active">
                    <i></i>
                </div>
                <span class="merchantName">深圳保税仓</span>
                    <span class="payPrice">
                    <span>0</span>
                </span>
            </div>
            <!--<li class="active">-->
                <!--<div class="ld1 ld">-->
                    <!--<div class="checkbox enableSelect active">-->
                        <!--<input type="hidden">-->
                        <!--<i></i>-->
                    <!--</div>-->
                    <!--<div class="img_view">-->
                        <!--<img src="../images/15411601_85X85.jpg">-->
                    <!--</div>-->
                <!--</div>-->
                <!--<div class="ld2 ld">-->
                    <!--<a>【价格含税】欧缇丽葡萄籽保湿爽肤水200ml</a>-->
                <!--</div>-->
                <!--<div class="ld3 ld">-->
                    <!--<span data-bind="text:attrsString"></span>-->
                <!--</div>-->
                <!--<div class="ld4 ld">¥149</div>-->
                <!--<div class="ld6 ld">-->
                    <!--<span class="midde">-->
                        <!--<a class="less"></a>-->
                        <!--<input class="quantity_txt">-->
                        <!--<a class="add"></a>-->
                        <!--<br>-->
                        <!--<span class="canDelivery"></span>-->
                    <!--</span>-->
                <!--</div>-->
                <!--<div class="ld7 ld">-->
                    <!--<span class="font18" data-bind="text:'¥'+totalPayPrice()">¥149</span>-->
                <!--</div>-->
                <!--<div class="ld8 ld">-->
                    <!--<span class="midde">-->
                        <!--<a href="">删除</a>-->
                    <!--</span>-->
                <!--</div>-->
            <!--</li>-->
        </ul>
        <div class="jiesuan">
            <div class="float_l">
                <div class="checkbox enableSelect active">
                    <i></i>
                </div>
                <span class="f14" style="margin-right: 36px;">全选</span>
                <span class="bd">已经选中<b class="selectNumber fb000a f18">0</b>件商品</span>
                <span class="bd2">总重量<b data-bind="text:checkedTotalWeight">0.00</b>kg</span>
                <p>
                    <a href="" id="delAll">清空购物车</a>
                    <!--<a href="" id="dels">删除</a>-->
                </p>
            </div>
            <div class="float_r">
                <div class="quantity">
                    <p>
                        <span>合计（不含运费）：</span>
                        ¥<em class="price fb000a f18">0.00</em>
                    </p>
                </div>
                <a class="pay">结算</a>
            </div>
        </div>
    </div>
    <div class="center">
        <div class="web_map_My">
            <a href="">
                关于我们
            </a>｜
            <a href="">
                联系我们
            </a>｜
            <a href="">
                触屏版
            </a>
            <span class="copyright">
                Copyright@华润万家有限公司  粤ICP备05036369号-4   ewj.com 版权所有
            </span>
        </div>
    </div>
</body>
</html>

yelingling/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <link rel="stylesheet" href="/static/css/login.css">
    <script type="text/javascript" src="/static/js/jquery-1.12.0.js"></script>
    <script type="text/javascript" src="/static/js/jquery.cookie.js"></script>
    <script type="text/javascript" src="/static/js/login_input.js"></script>
    <script type="text/javascript" src="/static/js/login.js"></script>
</head>
<body>
    <div class="header">
        <div class="header_center">
            <img src="/static/images/4312385.png" alt="">
            <div class="header_center_r">
                <div>
                    您好，欢迎您来到华润e万家！
                    <span>|</span>
                    <a href="">帮助中心</a>
                </div>
            </div>
        </div>
    </div>
    <div class="body_center">
        <div class="body_center_h">
            <h1>用户登入</h1>
            <a href="{% url 'huarun:register' %}">新用户注册</a>
        </div>
        <div class="login_body">
            <a href="" class="img_a"><img src="/static/images/15401900.jpg" alt=""></a>
            <div class="login_body_r">
                <form action="{% url 'huarun:login' %}" method="post" >
                      {% csrf_token %}
                    <p>
                        <label>登录名：</label>
                        <input placeholder="邮箱/用户名/已验证手机" class="input" id="username" name="username1">
                        <span class="reg_span">{{ msg }}</span>
                    </p>
                    <p>
                        <label>密码：</label>
                        <input type="password" placeholder="请输入您的密码" class="input" id="password" name="password1">
                        <span class="reg_span"></span>
                    </p>
                    <p>
                        <label>验证码：</label>
                        <input  placeholder="请填写验证码" class="text_input" id="text" >
                        <span class="text_input_span"></span>
                        <a href="" class="text_input_a">看不清，换一张？ </a>
                        <span class="reg_span"></span>
                    </p>
                    <p class="checkbox_p">
                        <span class="checkbox">
                            <input  type="hidden" value="false">
                            <i></i>
                        </span>
                        自动登录
                        <a href="">忘记密码</a>
                    </p>
                    <p class="button">
                        <button type="submit" id="submit">登录</button>
                    </p>
                </form>
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="foot_center">
            <a href="">关于我们</a>
            |
            <a href="">联系我们</a>
            |
            <a href="">触屏版</a>
            <span>Copyright@华润万家有限公司  粤ICP备05036369号-4   ewj.com 版权所有</span>
        </div>
    </div>
</body>
</html>

yelingling/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
    <link rel="stylesheet" href="/static/css/register.css">
    <link rel="stylesheet" href="/static/css/login.css">
    <script type="text/javascript" src="/static/js/jquery-1.12.0.js"></script>
    <script type="text/javascript" src="/static/js/jquery.cookie.js"></script>
    <script type="text/javascript" src="/static/js/register.js"></script>
    <script type="text/javascript" src="/static/js/login_input.js"></script>
</head>
<body>
    <div class="header">
        <div class="header_center">
            <img src="/static/images/4312385.png" alt="">
            <div class="header_center_r">
                <div>
                    您好，欢迎您来到华润e万家！
                    <span>|</span>
                    <a href="">帮助中心</a>
                </div>
            </div>
        </div>
    </div>
    <div class="body_center">
        <div class="body_center_h">
            <h1>用户登入</h1>
            <a href="{% url 'huarun:login' %}">用户登录</a>
        </div>
        <div class="reg_body">
            <div class="reg_body_c">
                <form action="{% url 'huarun:register' %}" method="post" >
                     {% csrf_token %}
                    <p>
                        <label for=""><span>*</span>用户名：</label>
                        <input type="text" placeholder="请输入您的用户名，支持4-20字符" class="input" id="username" name="username">
                        <span class="reg_span">{{ msg }}</span>
                    </p>
                    <p>
                        <label for=""><span>*</span>手机号码：</label>
                        <input type="text" placeholder="请输入您的手机号码" class="input" id="phoneNum" name="tel">
                        <span class="reg_span"></span>
                    </p>
                    <p>
                        <label for=""><span>*</span>验证码：</label>
                        <input type="text" placeholder="请填写验证码" class="text_input" id="text" name="text2">

                        <span class="text_input_span"></span>
                        <a href="" class="text_input_a">看不清，换一张？</a>
                        <span class="reg_span"></span>
                    </p>
                    <p>
                        <label for=""><span>*</span>短信验证码：</label>
                        <input type="text" placeholder="输入短信验证码" class="text_input" id="phoneText" name="text3">
                        <button class="btn">获取短信验证码</button>
                        <span class="reg_span"></span>
                    </p>
                    <p>
                        <label for=""><span>*</span>设置密码：</label>
                        <input type="password" placeholder="请设置您的密码，支持6-20位字符，区分大小写" class="input" id="password" name="password">
                        <span class="reg_span"></span>
                    </p>
                    <p>
                        <label for=""><span>*</span>确认密码：</label>
                        <input type="password" placeholder="请确认密码" class="input" id="a_password">
                        <span class="reg_span"></span>
                    </p>
                    <p>
                        <label for="">推广码：</label>
                        <input type="text" placeholder="输入推广码（可不填）" class="input" id="promo">
                    </p>
                    <p class="checkbox_p">
                        <span class="checkbox">
                            <input type="hidden" value="false" id="checkbox">
                            <i></i>
                        </span>
                        我已阅读并同意
                        <a href="" class="reg_a">e万家服务协议</a>
                        <span class="reg_span"></span>
                    </p>
                    <p class="button">
                        <button type="submit" id="submit">注册</button>
                    </p>
                </form>
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="foot_center">
            <a href="">关于我们</a>
            |
            <a href="">联系我们</a>
            |
            <a href="">触屏版</a>
            <span>Copyright@华润万家有限公司  粤ICP备05036369号-4   ewj.com 版权所有</span>
        </div>
    </div>
</body>
</html>